# Cloudflare Workers 配置文件
# 用于通过 Dashboard 部署时的参考配置

name = "supplier-form-api"
main = "worker.js"
compatibility_date = "2024-06-11"
compatibility_flags = ["nodejs_compat"]

# KV 命名空间绑定
[[kv_namespaces]]
binding = "SUPPLIER_APPLICATIONS"
id = "YOUR_SUPPLIER_APPLICATIONS_NAMESPACE_ID"
preview_id = "YOUR_SUPPLIER_APPLICATIONS_PREVIEW_ID"

[[kv_namespaces]]
binding = "ADMIN_USERS"
id = "YOUR_ADMIN_USERS_NAMESPACE_ID"
preview_id = "YOUR_ADMIN_USERS_PREVIEW_ID"

[[kv_namespaces]]
binding = "ADMIN_SESSIONS"
id = "YOUR_ADMIN_SESSIONS_NAMESPACE_ID"
preview_id = "YOUR_ADMIN_SESSIONS_PREVIEW_ID"

# 环境变量
[vars]
FRONTEND_URL = "https://supplier-form.pages.dev"
JWT_SECRET = "your-jwt-secret-key-change-this-in-production"

# 路由配置
[[routes]]
pattern = "api.your-domain.com/*"
zone_name = "your-domain.com"

# 或者使用 workers.dev 子域名
# route = "supplier-form-api.your-account.workers.dev/*"